version: "3"
services:
  workspace:
    build:
      dockerfile: Dockerfile
      context: .
    init: true
    container_name: workspace
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace